
#==============================================================================================#
#============================================IMPORT============================================#
#==============================================================================================#
import = [
  "~/.config/alacritty/themes/monokai_charcoal_white.toml"
]

#default theme
#import = [
#  "~/.config/alacritty/themes/default_theme.toml"
#]





#==============================================================================================#
#===========================================GENERAL============================================#
#==============================================================================================#
live_config_reload = true
working_directory = "None"





#==============================================================================================#
#===========================================shell============================================#
#==============================================================================================#
[shell]
program = "/bin/bash"
args = ["-l"]





#==============================================================================================#
#=========================================clipboard============================================#
#==============================================================================================#
[selection]
save_to_clipboard = true





#==============================================================================================#
#===========================================WINDOW=============================================#
#==============================================================================================#
[window]
padding = { x = 2, y = 2 }
opacity = 0.6
blur = true 
startup_mode = "Windowed"
title = "Alacritty"
decorations_theme_variant = "None"





#==============================================================================================#
#===========================================SCROLLING=========================================#
#==============================================================================================#
[scrolling]
history = 1000





#==============================================================================================#
#==============================================CURSOR=========================================#
#==============================================================================================#
[cursor]
unfocused_hollow = true





#==============================================================================================#
#==========================================FONTS SETTINGS======================================#
#==============================================================================================#
[font]
size = 11.25

[font.offset]
x = 0
y = 0

[font.normal]
family = "Monospace"
style = "Bold"

[font.bold]
family = "Monospace"
style = "Bold"

[font.bold_italic]
family = "Monospace"
style = "Bold"

[font.italic]
family = "Monospace"
style = "Bold"





#==============================================================================================#
#=======================================KEYBOARD BINDINGS======================================#
#==============================================================================================#
[keyboard]
bindings = [
{ key = "C", mods = "Control|Shift", action = "Copy" },
{ key = "V", mods = "Control|Shift", action = "Paste" },
{ key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "T", mods = "Control", action = "CreateNewWindow" },
{ key = "L", mods = "Control", chars = "\u000c" },
{ key = "L", mods = "Control", action = "ClearHistory" },
{ key = "F", mods = "Control", action = "SearchBackward" },
]
